---
# tasks file for httpd
- name: install httpd
  package: name=httpd state=installed 

- name: copy a conf file
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify: start apache

- name: Sample Page
  copy:
    content: "<h1> This is from SSM </h1>"
    dest: /var/www/html/index.html
    
